[package]
name = "transfer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "transfer-server"
path = "src/server.rs"

[[bin]]
name = "transfer-client"
path = "src/client.rs"

[dependencies]
tonic = "0.7"
prost = "0.10"
tokio = { version = "1.0", features = ["full"] }
clap = { version = "3.2.6", features = ["derive"] }

[build-dependencies]
tonic-build = "0.7"
